server:
  port: ${SERVER_PORT:9009}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:@@@@@}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:user}
      roles: INTERNAL

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    root: INFO
    io.store.ua: DEBUG